export default [
  {
    user_id: 1,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 2,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 3,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 4,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 5,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 6,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 7,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 8,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 9,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
  {
    user_id: 10,
    real_name: 'real_name',
    user_name: 'user_name',
    clicks: 'clicks',
    ctr: 'ctr',
    amount: 'amount',
    remain_amount: 'remain_amount',
  },
];
